let width = 750;
let height = 750;

//creating two arrays to hold the lefthand and the righthand colors
let colorsRight = [];
let colorsLeft = [];

//specify the amount of boxes in the X and Y direction
let tileCountX = 10;
let tileCountY = 10;

function setup(){
  createCanvas(width,height);
  colorMode(HSB);
  noStroke();

  //calls the shakeColors fucntion
  shakeColors();
}

function draw(){

}

//populates the color arrays with random colors
function shakeColors() {
  //for as many boxes there are in the Y direction
  for(let i = 0; i<tileCountY; i++){
    //add a new color generated by the genRandom function
    colorsLeft.push(genRandomCol());
  }
  for(let i = 0; i<tileCountY; i++){
    //add a new color generated by the genRandom function
    colorsRight.push(genRandomCol());
  }
}

//generates 3 random values for R, G and B and creates a color object with them
function genRandomCol(){
  let col1 = floor(random(0,255));
  let col2 = floor(random(0,255));
  let col3 = floor(random(0,255));
  let randomColor = color(col1,col2,col3);
  //return the color object that was created
  return randomColor;
}
